version: "3.4"

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    env_file:
      - .env
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7.3:/meili_data
